<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms and Conditions - Happy Folks Club</title>
    <link rel="shortcut icon" type="image/jpg" href="./static/img/logo.jpeg" />
    <link rel="stylesheet" href="./static/styles/template.css">
    <link rel="stylesheet" href="./static/styles/style.css">
    <link rel="stylesheet" href="./static/styles/terms.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <?php include 'navbar.php'; ?>

    <div class="content">

        <div class="terms">

            <h1>Terms and Conditions</h1>

            <br>

            <ul>
                <li>
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </li>
                <br>
                <li>
                    This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name www.happyfolksclub.com (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”).
                </li>
                <br>
                <li>
                    The Platform is owned by, ISBR Business School, a company incorporated under the Companies Act, 1956 with its registered office at Electronic City, Phase 1, No. 107, Bangalore- 560100 (hereinafter referred to as "Platform Owner", “we”, “us”, “our”).
                </li>
                <br>
                <li>
                    Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, “Services”). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
                </li>
                <br>
                <li>
                    For the purpose of these Terms of Use, wherever the context so requires "you", “your” or "user" shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
                </li>
                <br>
                <li>
                    ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
                </li>
                <br>
                <li>
                    The use of Platform and/or availing of our Services is subject to the following Terms of Use:
                    <ol>
                        <li>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</li>
                        <li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</li>
                        <li>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.</li>
                        <li>The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.</li>
                        <li>You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</li>
                        <li>You agree to pay us the charges associated with availing the Services.</li>
                        <li>You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.</li>
                        <li>You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information.</li>
                        <li>You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.</li>
                        <li>You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys’ fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.</li>
                        <li>In no event will the Platform Owner be liable for any indirect, consequential, incidental, special or punitive damages, including without limitation damages for loss of profits or revenues, business interruption, loss of business opportunities, loss of data or loss of other economic interests, whether in contract, negligence, tort or otherwise, arising from the use of or inability to use the Services, however caused and whether arising in contract, tort, negligence, warranty or otherwise, exceed the amount paid by You for using the Services giving rise to the cause of action or Rupees One Hundred (Rs. 100) whichever is less.</li>
                        <li>Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.</li>
                        <li>These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.</li>
                        <li>All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Bangalore, Karnataka.</li>
                        <li>All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.</li>
                        <li>Refund not applicable.</li>
                    </ol>
                </li>
            </ul>
            <br>
            <br>
            <h3>Privacy Policy</h3>
            <div>
                <br>
                <h4>This Privacy Policy statement discloses the privacy practices for this Application / website and all its products (hereinafter referred to as “Service”), hosted by “Audition Update.”</h4>
                <h4>We realize that you care how your information is processed and shared, and we appreciate your trust in us to do that carefully and sensibly. This document describes our Privacy Policy.</h4>
                <h4>By registering your details with us you confirm that you have read, understood, and agreed to the provisions of this Privacy Policy. For the purpose of this Privacy Policy, the terms “User” shall not only mean the “Registered User” in accordance with the provisions of Terms of Service but also every person visiting all the products or the website.</h4>
                <br>
            </div>
            <ol>
                <li>
                    <br>
                    <b>Information We Collect</b>
                    <br>
                    <ul>
                        <br>
                        <li>We collect personal information from Users who visit this Application / Site and use our Service. Because of the nature of our Service, we must collect from Users personal information such as (at the minimum):
                            <ol>
                                <li>First and last name</li>
                                <li>Username</li>
                                <li>Email address, to be used as a login;</li>
                                <li>Password;</li>
                                <li>Billing information such as billing address and credit card information where necessary;</li>
                                <li>Phone;</li>
                                <li>Country;</li>
                                <li>Address, city, state, zip/pin code;</li>
                                <li>Photographs, etc.</li>
                            </ol>
                        </li>
                        <li>We may also ask Users to provide additional personal information such as:
                            <br>
                            <ul>
                                <li>
                                    Company name;
                                </li>
                                <li>Title;</li>
                                <li>Educational institution;</li>
                                <li>Personal details that the User may opt-out of by not entering data when asked.</li>
                            </ul>
                            <br>
                        </li>
                        <li>We use the User’s registration information to authenticate Users and provide access to the Service. We also use the email addresses used in the registration information to communicate with the Users. From time to time, we may contact the User via email to notify them of changes to our Service, scheduled maintenance, information about Services and promotional material.</li>
                        <li>With active consent, the User’s email address can be used to send them updates from us. Users can opt-out of such emails at any time by contacting us, but they will still receive emails such as receipts, confirmation emails and customer Service updates, and other necessary information to provide the Service to the User.</li>
                        <li>Information that is provided by meeting organizers such as: Username, email address and any other business contact and meeting subject contact are considered confidential to the User. When the Clients register with one of our Users for an online Filing, that information is provided by the User. We may store that information to fulfil our obligations to our Users.</li>
                        <li>We will not use the information to send marketing information for Services or the third party offers to the Clients and Users. The User and Clients should be aware that any personal information they submit while in-session and chatting can be read, collected, or used by the User and other Participants. We will not view information except as necessary to appropriately support the Service.</li>
                        <li>We collect only personal information that the User chooses to provide voluntarily registering to our Products / Service. We shall advise the User which information is mandatory to provide and what they do not have to enclose.</li>
                    </ul>
                </li>
                <li><b>Password</b></li>
                <ul>
                    <li>
                        The User’s Account information, username, password, and user profile are password-protected so that they have secure access to entering and editing personal data. It is the User’s responsibility to protect the security of their password. Access to the Service is protected by a unique username and password that is known to the User only. We have designed internal security processes that encrypt the User’s password to protect it from being divulged or accessed by anyone other than the User. Neither our employees nor any of our contractors can obtain or access to the User’s password. Neither our employees nor any of our contractors will ask the User for their password via mail, email, telephone or in any other unsolicited manner.
                    </li>
                </ul>
            </ol>
            <li>
                <b>User Access and Choice</b>
                <br>
                <ul>
                    <li>
                        If your personal information changes, or if you no longer desire our Service, you may correct, update, remove or request deletion by making the change on our member information page and/or by emailing us at contact@auditionupdate.in . We will respond to your request within 30 working days. We will retain your information for as long needed to provide you services. We will retain and use your information as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements. We are required to store all personal data of the User and all information regarding the User’s Account (together with all data, the Content, email messages, statistics, Users and Clients’ data) during 90 days upon the Account is cancelled or the Service (Agreement) is terminated. We will not process above data for other purposes than storage of the data only, subject to binding legal provisions or obligations imposed on us by public authorities. We shall store the above data only in order to resume the User’s Account by the User in accordance with the Terms of Service and to perform its duties specified in binding legal provisions or imposed on us by public authorities. As of the date on which the above term (90 days) expires, we shall cease to process the data and all data shall be permanently deleted from the Service.
                    </li>
                    <li>
                        We will ask for the User’s consent before we use or share their information for any purpose other than the reason they provided or as otherwise provided by this policy. In order to know the User’s preferences, we will require an action on their part, such as checking the appropriate option, to indicate their consent.
                    </li>
                </ul>
            </li>
            <li>
                <b>Mailing Policy</b>
                <br>
                <ol>
                    <li>
                        When the User sends us an email, we use their email address to thank them for their comment and/or reply to their question, and we will store their communication and our reply for any future correspondence. Beyond our initial reply, we will never use the User’s email address to send them any unsolicited messages or information, nor will we share it with or sell it to anyone else for such use.
                    </li>
                    <li>
                        When the User agrees to receive marketing information about our services and products or our commercial partners, we use their email address and any other information they give us to provide them with the information about our services and products or our commercial partners, until they ask us to stop (using the ‘unsubscribe’ instructions provided with each email, and/or on the site where they signed up, and/or as we otherwise provide).
                    </li>
                    <li>
                        We will never use the User’s email address or other information to provide them with any unsolicited messages or information (unless that is part of the service they are requesting).
                    </li>
                </ol>
            </li>
            <li>
                <b>Information Sharing</b>
                <br>
                <ul>
                    <li>
                        We do not sell or rent the User’s Personal Information to third parties for marketing purposes unless they have granted us permission to do so. In case, for any reason we believe that disclosure is necessary to protect our rights, protect your safety or the safety of others, investigate fraud, or respond to a government request, the information shall be disclosed to concerned authority or shall be used to such extent as reasonably required.
                    </li>
                    <li>
                        In case we are involved in a merger, acquisition, or sale of all or a portion of its assets, you will be notified via email and/or wide a prominent notice on our Web site of any change in ownership or uses of your personal information, as well as any further choices you may have regarding your personal information.
                    </li>
                </ul>
            </li>
            <li>
                <b>
                    Minor’s Privacy Policy
                </b>
                <ul>
                    <li>
                        A Minor is a person who has not attained the age of majority as per the applicable laws of the land.
                    </li>
                    <li>
                        It is required for the user to ensure that he / she has attained the age of majority as per the applicable laws of the land.
                    </li>
                    <li>
                        If a user is of minor age, he / she has to ensure that he / she is utilizing the service of Audition Update in the supervision of parental control.
                    </li>
                    <li>
                        Since we may amend these policies from time to time, you are requested and responsible to access, review such changes to the policies. If you continue to access the Website / Application after such amendments, you are deemed to have accepted and agreed to the changes.
                    </li>
                </ul>
            </li>
            <li>
                <b>Tracking Technologies</b>
                <br>
                <ul>
                    <li>As is true of most Applications / web sites, we gather certain information about visitors to our Application / site automatically and store it in log files.</li>
                    <li>The Application / site use information includes, but is not limited to, the following: the domain names, operating system in use (e.g. Macintosh, Windows), browser (e.g. Google Chrome, Mozilla Firefox, Internet Explorer) and version, the website which referred the User to us, and other similar information. This information may be aggregated to measure the number of visits, average time spent on our Application / website, pages viewed, time and date of visits, and other similar information. We may use and disclose site use information, for example, to measure the use of our Application / website, improve the content, explain the utility of our website and services we provide, and to extend their functionality.</li>
                    <li>Similar to other commercial Applications / websites, the technology called “cookies” may be used to provide the User with tailored information. A cookie is a small piece of data that an Application / website can send to the User’s browser, which may then be stored on their hard drive, so we can recognize the user when they return. The User may be able to set their browser to notify them when they receive a cookie. Our cookies collect general information that enhances our ability to serve the User and measure the utility of our Application / website.</li>
                    <li>A cookie cannot read personal data on a hard disk or read cookie files created by other Applications / sites; indeed, the only Personal Information a cookie can contain is information the User supplies himself or herself. Accepting the cookies used on our website may give us access to information about the User’s browsing behaviour, which we may use to personalize their experience and track user traffic patterns, and to merge this info when the user registers. We do this in order to determine the usefulness of our Application / website information to our Users and to see how effective our navigational structure is in helping users reach that information.</li>
                    <li>The User may browse most of Application / website without accepting cookies; however, some Application / website functionality may be lost by the User disabling cookies on their computer / mobile. Information we collect may be used to enhance the use of our Application / website, and to provide the user with a service that they ordered, arrange the website in the most customer friendly way, communicate special offers and featured items, and/or respond to any questions and suggestions.</li>
                    <li>The use of cookies by any partners, affiliates, tracking utility company or service providers is not covered by our privacy statement. We do not have access or control over these cookies.</li>
                </ul>
            </li>

            <li>
                <b>Information Security</b>
            <li>
                We believe that keeping Personal Information secure is one of our most significant responsibilities.
            </li>
            <li>
                We recognize the importance of respecting the privacy of those who decided to entrust their sensitive information with the User. We make every effort to safeguard their security. We will never use the information about the Clients that Users collect within our Services to send any information other than expressly provided by their Clients, nor will we share it with or sell it to anyone else for such use.
            </li>
            <li>
                We restrict access to Personal Information about the User to those employees and others who need to know that information to assist us in our business, or to provide products or services to the user. We safeguard personal information, according to the established security standards and procedures, by maintaining physical, electronic, and procedural safeguards to the personal data information.
            </li>
            <li>
                All our Users’ and Clients’ information, not just the sensitive information mentioned above, is restricted in our offices. Only employees who need the information to perform a specific job (e.g. our billing clerk or a customer service representative) are personally granted access to sensitive information.
            </li>
            <li>
                When we request Users or customers to enter sensitive information, such as their name, geographical address, email address, and a credit card number, it is encrypted and protected with the best encryption software in the industry SSL and processed through a reputable payment processor. While on the secure page, such as our order form, the lock icon at the bottom of web browsers, e.g. Mozilla Firefox or Microsoft Internet Explorer, becomes locked, as opposed to unlocked or open, when the User is just ‘surfing’.
            </li>
            <li>
                We store our servers in a highly secure server environment, with surveillance and support to prevent unauthorized access and maintain data security.
            </li>
            <li>
                We cannot guarantee the security of the User’s data while it is being transmitted over the Internet and through servers that are beyond our control. We strive to protect the User’s personal information but we cannot ensure or warrant the security of any information they transmit to our Application / website or Services. Any data transmissions the User makes over the Internet are done so at their own risk. Once we receive the data transmission, we make our best efforts to ensure its security and privacy on our systems.
            </li>
            </li>
            <li>
                <b>Additional Information</b>
                <br>
                <ul>
                    <li>
                        <b>Links to Third Party Sites</b>
                        <br>
                        Our Application / Site includes links to other Web sites whose privacy practices may differ from those of ours. If you submit personal information to any of those sites, your information is governed by their privacy statements. We encourage you to carefully read the privacy statement of any Web site you visit.
                    </li>
                    <li>
                        <b>Testimonials</b>
                        <br>
                        With your consent, we may post your testimonial along with your name. If you wish to update or delete your testimonial, you can contact us at siddharth@isbr.in
                    </li>
                    <li>
                        <b>
                            Changes to this Policy
                        </b>
                        <br>
                        We may update this privacy statement to reflect changes to our information practices. If we make any material changes, we will notify you by means of a notice on this Application / Site prior to the change becoming effective. We encourage you to periodically review this page for the latest information on our privacy practices.
                    </li>
                    <li>
                        <b>Contact</b>
                        <br>
                        We need the User’s help in keeping the Personal Information they have shared with us accurate and up-to-date.
                    </li>
                </ul>
            </li>
        </div>
    </div>


    <?php include 'footer.php'; ?>
</body>
<script src="./static/js/main.js"></script>


</html>